apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime
  labels:
    app: realtime
spec:
  selector:
    matchLabels:
      app: realtime
  replicas: 2
  template:
    metadata:
      labels:
        app: realtime
    spec:
      containers:
      - name: realtime
        image: gbaeke/flux-rt
        livenessProbe:
          httpGet:
            path: /index.html
            port: 8080
        readinessProbe:
          httpGet:
            path: /index.html
            port: 8080
        env:
        - name: REDISHOST
          value: "$(REDISSERVICE).$(REDISNAMESPACE):6379"
        resources:
          requests:
            cpu: 25m
            memory: 50Mi
          limits:
            cpu: 150m
            memory: 150Mi
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: git-ops-frontend
  namespace: weave-gitops
  labels:
    app: realtime
    app.kubernetes.io/name: weave-gitops
    app.kubernetes.io/component: git-ops-frontend
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the git-ops-frontend service.
  # type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: realtime
    app.kubernetes.io/name: weave-gitops
    app.kubernetes.io/component: git-ops-frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weave-gitops
  namespace: weave-gitops
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - realtime.weaveworks.tech
    secretName: realtime-weaveworks.tech-crt
  rules:
  - host: realtime.weaveworks.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: git-ops-frontend
            port:
              number: 80


